#!/usr/bin/env bash
# Nightly snapshot of the meta schema (customers / api_keys / usage_log).
#
# Only the meta schema is backed up — it's the only data that cannot
# be regenerated by re-running ingests. Everything in staging (ONSPD,
# Boundary-Line, flood polygons, EPC, etc.) is re-ingestible from
# source, so paying disk for daily dumps of those is wasteful.
#
# Run via systemd timer (see scripts/geo-mcp-backup.{service,timer}).
# Ad-hoc: just run this script.
set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
readonly BACKUP_DIR="${GEO_MCP_BACKUP_DIR:-/data/backups}"
readonly KEEP_N="${GEO_MCP_BACKUP_KEEP:-30}"

set -a
source "${REPO_ROOT}/.env"
set +a

mkdir -p "$BACKUP_DIR"
readonly STAMP=$(date -u +%Y%m%d-%H%M%S)
readonly OUT="${BACKUP_DIR}/meta-${STAMP}.sql.gz"

echo "[backup] dumping meta schema → ${OUT}"
export PGPASSWORD="$MCP_ADMIN_PASSWORD"
pg_dump \
    -h 127.0.0.1 -p 5432 \
    -U mcp_admin \
    -d "$POSTGRES_DB" \
    --schema=meta \
    --no-owner --no-privileges \
    --clean --if-exists \
    | gzip > "${OUT}.part"
mv "${OUT}.part" "$OUT"

size=$(du -h "$OUT" | awk '{print $1}')
echo "[backup] wrote ${OUT} (${size})"

# Retain the most recent N; drop older.
mapfile -t obsolete < <(ls -1t "${BACKUP_DIR}"/meta-*.sql.gz 2>/dev/null | tail -n +$((KEEP_N + 1)) || true)
for f in "${obsolete[@]}"; do
    echo "[backup] pruning ${f}"
    rm -f "$f"
done

echo "[backup] ${#obsolete[@]} pruned; $(ls -1 "${BACKUP_DIR}"/meta-*.sql.gz 2>/dev/null | wc -l) retained."
