#!/usr/bin/env bash
# Nightly snapshot of the meta schema (customers / api_keys / usage_log).
#
# Only the meta schema is backed up — it's the only data that cannot
# be regenerated by re-running ingests. Everything in staging (ONSPD,
# Boundary-Line, flood polygons, EPC, etc.) is re-ingestible from
# source, so paying disk for daily dumps of those is wasteful.
#
# Run via systemd timer (see scripts/geo-mcp-backup.{service,timer}).
# Ad-hoc: just run this script.
set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
readonly BACKUP_DIR="${GEO_MCP_BACKUP_DIR:-/data/backups}"
readonly KEEP_N="${GEO_MCP_BACKUP_KEEP:-30}"

set -a
source "${REPO_ROOT}/.env"
set +a

mkdir -p "$BACKUP_DIR"
readonly STAMP=$(date -u +%Y%m%d-%H%M%S)
readonly OUT="${BACKUP_DIR}/meta-${STAMP}.sql.gz"

echo "[backup] dumping meta schema → ${OUT}"
export PGPASSWORD="$MCP_ADMIN_PASSWORD"
pg_dump \
    -h 127.0.0.1 -p 5432 \
    -U mcp_admin \
    -d "$POSTGRES_DB" \
    --schema=meta \
    --no-owner --no-privileges \
    --clean --if-exists \
    | gzip > "${OUT}.part"
mv "${OUT}.part" "$OUT"

size=$(du -h "$OUT" | awk '{print $1}')
echo "[backup] wrote ${OUT} (${size})"

# Retain the most recent N; drop older.
mapfile -t obsolete < <(ls -1t "${BACKUP_DIR}"/meta-*.sql.gz 2>/dev/null | tail -n +$((KEEP_N + 1)) || true)
for f in "${obsolete[@]}"; do
    echo "[backup] pruning ${f}"
    rm -f "$f"
done

echo "[backup] ${#obsolete[@]} pruned; $(ls -1 "${BACKUP_DIR}"/meta-*.sql.gz 2>/dev/null | wc -l) retained."

# Offsite sync. Skipped silently if no rclone remote is configured so the
# local backup path works standalone. The remote name (default: r2) and
# destination path are env-overridable; set GEO_MCP_OFFSITE_REMOTE="" to
# disable entirely.
readonly OFFSITE_REMOTE="${GEO_MCP_OFFSITE_REMOTE:-r2}"
readonly OFFSITE_PATH="${GEO_MCP_OFFSITE_PATH:-geo-mcp-backups}"
# systemd's default PATH doesn't include ~/.local/bin, so resolve rclone
# explicitly with a cascade: explicit override → PATH → user-local.
rclone_bin="${GEO_MCP_RCLONE:-$(command -v rclone || echo "$HOME/.local/bin/rclone")}"
if [[ -n "$OFFSITE_REMOTE" ]] && [[ -x "$rclone_bin" ]] \
   && "$rclone_bin" listremotes 2>/dev/null | grep -q "^${OFFSITE_REMOTE}:$"; then
    echo "[backup] syncing ${BACKUP_DIR} → ${OFFSITE_REMOTE}:${OFFSITE_PATH}"
    # --include pattern keeps irrelevant files (lock files, partial
    # downloads, old restore-drill scratch) out of the offsite copy.
    "$rclone_bin" sync "${BACKUP_DIR}" "${OFFSITE_REMOTE}:${OFFSITE_PATH}" \
        --include 'meta-*.sql.gz' \
        --fast-list
    echo "[backup] offsite sync done"
else
    echo "[backup] offsite sync skipped (rclone '${rclone_bin}' missing or remote '${OFFSITE_REMOTE}' not configured)"
fi
